### PR TITLE
Fork

### PR DESCRIPTION
**Pull request by roanutil**
- Port tests to XCTest
- Change swiftformat config
- Change SwiftLint config
- Resolve lint warnings
- Port documentation to DocC
- Change CI workflow
- Remove Spectre dependency
- Change PathKit dependency to MFB Tech fork
- Add linux dev container
- Fix build error in tests on linux

### CODE REVIEW

**Review by r-jarvis — COMMENTED** [review]
For consistency of our repos, should we also add `SwiftFormat` to this project?

**Comment by r-jarvis** [comment]
I'm seeing a handful of Sendable warnings. Did you want to handle that in this initial PR or wait on it?

**Comment by roanutil** [comment]
> I'm seeing a handful of Sendable warnings. Did you want to handle that in this initial PR or wait on it?

Wait on it. I tried to keep this PR "structural".

**Comment by roanutil** [comment]
> For consistency of our repos, should we also add `SwiftFormat` to this project?

What do you mean? Isn't there already a config file for it?

**Comment by r-jarvis** [comment]
My bad... So many files I missed the swiftformat config

**Review by r-jarvis — APPROVED** [review]

**Pull request merged**
